name: Run bot
on:
  schedule:
  - cron: '01 * * * *'  # every 5 minutes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # 
    - name: Install dependencies
      run: |
        pip install tweepy
    - name: run the bot
      run: |
        python main.py
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.txt
        git commit -m "Update file"
        git push origin main
      env:
        TWITTER_API_KEY : ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY : ${{ secrets.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN : ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET : ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
