name: Run bot
on:
  schedule:
    - cron: '*/60 * * * *'
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # 
    - name: Install dependencies
      run: |
        pip install tweepy
    - name: run the bot
      run: |
        python main.py
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "Github Actions"
        git add last_tweet_index.txt
        git commit -m "Update last tweet index"
        git push origin main
      env:
        TWITTER_API_KEY : ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY : ${{ secrets.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN : ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET : ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
